const thuTucHanhChinh = [
    {id: "1.007014", name: "Khai thuế GTGT đối với phương pháp khấu trừ đối với hoạt động sản xuất kinh doanh"},
    {id: "1.007016", name: "Khai thuế Giá trị gia tăng đối với phương pháp trực tiếp trên giá trị gia tăng"},
    {id: "1.007022", name: "Khai thuế Giá trị gia tăng đối với phương pháp trực tiếp trên doanh thu"},
    {id: "1.007026", name: "Khai thuế thu nhập doanh nghiệp tính theo tỷ lệ % trên doanh thu"},
    {id: "1.007033", name: "Tiêu huỷ hoá đơn đặt in mua của cơ quan thuế"},
    {id: "1.007037", name: "Hoàn thuế giá trị gia tăng của doanh nghiệp, tổ chức"},
    {id: "1.007041", name: "Khai thuế tiêu thụ đặc biệt đối với cơ sở sản xuất, pha chế xăng sinh học"},
    {id: "1.007042", name: "Đăng ký thuế trong trường hợp tạm ngừng hoạt động, kinh doanh; tiếp tục hoạt động, kinh doanh trước thời hạn"},
    {id: "1.007043", name: "Chấm dứt hiệu lực mã số thuế của doanh nghiệp, hợp tác xã bị chia, bị sáp nhập, bị hợp nhất; Chấm dứt hoạt động đơn vị phụ thuộc của doanh nghiệp và hợp tác xã"},
    {id: "1.007277", name: "Khai lệ phí trước bạ nhà, đất/ Miễn lệ phí trước bạ nhà, đất"},
    {id: "1.007607", name: "Chấm dứt hiệu lực mã số thuế"},
    {id: "1.007674", name: "Khai thuế TNCN đối với cá nhân có thu nhập từ chuyển nhượng bất động sản; thu nhập từ nhận thừa kế và nhận quà tặng là bất động sản"},
    {id: "1.007695", name: "Khai; miễn, giảm thuế sử dụng đất phi nông nghiệp/ Khai thuế sử dụng đất nông nghiệp"},
    {id: "1.007699", name: "Khai lệ phí trước bạ tàu thuyền đánh cá, tàu thuyền vận tải thuỷ nội địa, tàu biển nếu thiếu hồ sơ gốc hoặc đóng mới tại Việt Nam"},
    {id: "1.007700", name: "Khai lệ phí trước bạ/ Miễn lệ phí trước bạ đối với tài sản khác theo quy định của pháp luật về lệ phí trước bạ (trừ tàu thuyền đánh cá, tàu thuyền vận tải thuỷ nội địa, tàu biển nếu thiếu hồ sơ gốc hoặc đóng mới tại Việt Nam)"},
    {id: "1.007721", name: "Miễn, giảm thuế tài nguyên đối với trường hợp cơ quan thuế quyết định miễn, giảm"},
    {id: "1.008309", name: "Khai quyết toán thuế thu nhập cá nhân đối với tổ chức, cá nhân trả thu nhập từ tiền lương, tiền công"},
    {id: "1.008321", name: "Khai quyết toán phí bảo vệ môi trường đối với khai thác khoáng sản"},
    {id: "1.008325", name: "Khai/ Khai quyết toán phí, lệ phí khác thuộc ngân sách nhà nước"},
    {id: "1.008335", name: "Khai thuế thu nhập doanh nghiệp đối với hoạt động chuyển nhượng bất động sản, khai thuế thu nhập doanh nghiệp từ hoạt động bán toàn bộ Công ty TNHH một thành viên do tổ chức làm chủ sở hữu dưới hình thức chuyển nhượng vốn có gắn với bất động sản theo lần phát sinh"},
    {id: "1.008340", name: "Khai thuế thu nhập cá nhân tháng/quý của tổ chức, cá nhân trả thu nhập thực hiện khấu trừ thuế đối với thu nhập từ đầu tư vốn, từ chuyển nhượng chứng khoán, từ bản quyền, từ nhượng quyền thương mại, từ trúng thưởng của cá nhân cư trú và cá nhân không cư trú; từ kinh doanh của cá nhân không cư trú; Tổ chức, cá nhân khi nhận chuyển nhượng vốn góp của cá nhân không cư trú"},
    {id: "1.008345", name: "Tra soát, điều chỉnh thông tin thu, nộp ngân sách nhà nước"},
    {id: "1.008346", name: "Khai quyết toán thuế thu nhập doanh nghiệp theo phương pháp doanh thu - chi phí"},
    {id: "1.008498", name: "Đăng ký thuế lần đầu đối với người nộp thuế là cá nhân, người phụ thuộc"},
    {id: "1.008500", name: "Đăng ký thuế lần đầu cho người phụ thuộc để giảm trừ gia cảnh của người nộp thuế thu nhập cá nhân - Trường hợp cá nhân ủy quyền đăng ký thuế cho cơ quan chi trả thu nhập"},
    {id: "1.008503", name: "Đăng ký thay đổi thông tin đăng ký thuế không làm thay đổi cơ quan thuế quản lý trực tiếp (trừ trường hợp đăng ký thuế theo cơ chế một cửa liên thông qua cơ quan đăng ký kinh doanh)"},
    {id: "1.008510", name: "Khôi phục mã số thuế"},
    {id: "1.008513", name: "Gia hạn nộp hồ sơ khai thuế"},
    {id: "1.008529", name: "Khai thuế thu nhập cá nhân đối với cá nhân có thu nhập từ chuyển nhượng vốn góp, cá nhân chuyển nhượng chứng khoán khai trực tiếp với cơ quan thuế và tổ chức, cá nhân khai thuế thay, nộp thuế thay cho cá nhân"},
    {id: "1.008538", name: "Khai thuế thu nhập cá nhân đối với cá nhân có thu nhập từ nhận thừa kế, quà tặng là các tài sản khác phải đăng ký quyền sở hữu, không phải là bất động sản"},
    {id: "1.008549", name: "Khai quyết toán thuế tài nguyên đối với cơ sở khai thác tài nguyên"},
    {id: "1.008559", name: "Hoàn thuế GTGT đối với trường hợp được hưởng ưu đãi miễn trừ ngoại giao"},
    {id: "1.008564", name: "Hoàn thuế khi chuyển đổi sở hữu, chuyển đổi doanh nghiệp, sáp nhập, hợp nhất, chia, tách, giải thể, phá sản, chấm dứt hoạt động đối với trường hợp không thuộc diện cơ quan thuế kiểm tra tại trụ sở của người nộp thuế"},
    {id: "1.008565", name: "Bù trừ, hoàn nộp thừa các loại thuế và các khoản thu khác"},
    {id: "1.008583", name: "Miễn, giảm thuế tài nguyên đối với trường hợp người nộp thuế tự xác định số thuế được miễn, giảm"},
    {id: "1.008588", name: "Nộp dần tiền thuế nợ"},
    {id: "1.008589", name: "Không tính tiền chậm nộp"},
    {id: "1.008590", name: "Gia hạn nộp thuế"},
    {id: "1.008591", name: "Thủ tục xác nhận thực hiện nghĩa vụ thuế"},
    {id: "1.008593", name: "Thông báo về phương pháp trích khấu hao TSCĐ/ Thông báo về việc chuyển lợi nhuận ra nước ngoài"},
    {id: "1.008759", name: "Đăng ký thuế trong trường hợp chia, tách, hợp nhất, sáp nhập tổ chức"},
    {id: "1.009825", name: "Thông báo/thay đổi thông tin số tài khoản/số hiệu ví điện tử"},
    {id: "1.010339", name: "Cấp/Điều chỉnh/Thay thế hóa đơn điện tử có mã của cơ quan thuế theo từng lần phát sinh"},
    {id: "1.010343", name: "Chuyển dữ liệu hóa đơn điện tử tới cơ quan thuế"},
    {id: "1.010337", name: "Đăng ký sử dụng hoá đơn điện tử/ Thay đổi nội dung đăng ký sử dụng hoá đơn điện tử/ ủy nhiệm lập hóa đơn điện tử/ Chuyển đổi áp dụng hóa đơn điện tử có mã của cơ quan thuế/Khai thác dữ liệu của chi nhánh, đơn vị phụ thuộc/Thông báo tạm ngừng sử dụng hóa đơn điện tử/Tích hợp hóa đơn điện tử với biên lai thu thuế, phí, lệ phí”"},
    {id: "1.010241", name: "Đăng ký thuế lần đầu đối với người nộp thuế là cá nhân có thu nhập thuộc diện chịu thuế thu nhập cá nhân hoặc có nghĩa vụ với NSNN (trừ cá nhân kinh doanh) - Trường hợp cá nhân đăng ký thuế trực tiếp với cơ quan thuế."},
    {id: "1.010701", name: "Thông báo sử dụng dịch vụ của Đại lý thuế/Thông báo tạm dừng, chấm dứt sử dụng dịch vụ của Đại lý thuế"},
    {id: "1.010949", name: "Thay đổi kỳ tính thuế giá trị gia tăng từ tháng sang quý"},
    {id: "1.011013", name: "Xử lý không hoàn trả số tiền thuế, tiền chậm nộp, tiền phạt nộp thừa đối với trường hợp người nộp thuế từ chối nhận lại số tiền nộp thừa"},
    {id: "1.011014", name: "Thủ tục bù trừ số tiền thuế, tiền chậm nộp, tiền phạt nộp thừa"},
    {id: "1.011022", name: "Khai thuế đối với hộ kinh doanh, cá nhân kinh doanh nộp thuế theo phương pháp kê khai"},
    {id: "1.011043", name: "Đăng ký mới/bổ sung thông tin đăng ký/thu hồi tài khoản truy cập Cổng thông tin điện tử đề khai thác sử dụng thông tin hóa đơn điện tử"},
    {id: "1.011046", name: "Đăng ký/thay đổi thông tin sử dụng tem điện tử"},
    {id: "1.011047", name: "Kế hoạch mua/mua bổ sung/đơn đề nghị mua tem điện tử thuốc lá hoặc tem điện tử rượu sản xuất để tiêu thụ trong nước"},
    {id: "1.011049", name: "Thông báo mất, cháy/kết quả hủy tem điện tử thuốc lá hoặc tem điện tử rượu sản xuất để tiêu thụ trong nước"},
    {id: "1.011051", name: "Đề nghị chuyển số lượng tem còn tồn khi sáp nhập, chia, tách/chuyển cơ quan thuế quản lý tem điện tử thuốc lá hoặc tem điện tử rượu sản xuất để tiêu thụ trong nước"},
    {id: "1.011520", name: "Khai, nộp vào ngân sách nhà nước tiền thu từ chuyển đổi sở hữu doanh nghiệp, đơn vị sự nghiệp công lập, nguồn thu từ chuyển nhượng vốn nhà nước và chênh lệch vốn chủ sở hữu lớn hơn vốn điều lệ tại doanh nghiệp"},
    {id: "1.013659", name: "Xử lý chứng từ điện tử đã lập sai"},
    {id: "1.014030", name: "Thủ tục kê khai và nộp thuế đã khấu trừ đối với các tổ chức quản lý nền tảng thương mại điện tử của hộ, cá nhân có hoạt động kinh doanh trên nền tảng thương mại điện tử"},
    {id: "1.014031", name: "Thủ tục kê khai, nộp thuế của cá nhân cư trú có hoạt động kinh doanh trên nền tảng thương mại điện tử không có chức năng thanh toán (chỉ áp dụng cho kỳ tính thuế nhỏ hơn ngày 06/04/2026)"},
    {id: "1.014033", name: "Thủ tục hoàn thuế của hộ, cá nhân có hoạt động kinh doanh trên nền tảng thương mại điện tử"},
    {id: "1.014976", name: "Quyết toán thuế thu nhập cá nhân đối với hộ kinh doanh, cá nhân kinh doanh"},
    {id: "1.014979", name: "Hoàn nộp thừa các loại thuế đối với hộ kinh doanh, cá nhân kinh doanh"},
    {id: "2.002321", name: "Đăng ký thuế đối với trường hợp chuyển đổi mô hình hoạt động của tổ chức (Chuyển đơn vị phụ thuộc thành đơn vị độc lập hoặc ngược lại)"},
    {id: "2.002233", name: "Khai quyết toán thuế/ Hoàn thuế đối với cá nhân cư trú có thu nhập từ tiền lương, tiền công quyết toán thuế trực tiếp với cơ quan thuế"},
    {id: "3.000083", name: "Giảm thuế nhập cá nhân đối với cá nhân, hộ kinh doanh, cá nhân kinh doanh gặp khó khăn do thiên tai, hoả hoạn, do bị tai nạn; mắc bệnh hiểm nghèo"},
    {id: "3.000088", name: "Miễn tiền chậm nộp"},
];